version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
    networks:
      - app-network

  web:
    build: .
    container_name: application
    ports:
      - "5000:5000"
    environment:
      - DEBUG=true
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - BG_COLOR=teal
      - FAIL_FLAG=False
    depends_on:
      - mongo
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge